name: test
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
       
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: php-actions/composer@v6
    
    - uses: php-actions/phpstan@v3
      with:
        php_version: 8.1
        path: src/         
