name: test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: test
      
    permissions:
      contents: read
      packages: write
       
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/upload-artifact@v3
      with:
         name: artifact-test
         path: .
         if-no-files-found: error 

    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        php_version: 8.1
        path: src/         
