name: test
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
       
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  
            
    - uses: php-actions/phpstan@v3
      with:
        php_version: 8.1
        path: tests/         
